### ISSUE TITLE
Stuck on Installing application

### ISSUE THREAD

**Issue by egoran2** [RedrootDEV/WhatsAppDesktop-NoStore#4]
Hello, looks like it's just stuck, how to check it?

Downloading: 5319275A.WhatsAppDesktop_2.2349.2.0_neutral__cv1g1gvanyjgm.msixbundle
Download complete.
Whatsapp process stopped.
Installing the application: 5319275A.WhatsAppDesktop_2.2349.2.0_neutral_~_cv1g1gvanyjgm.msixbundle

**Comment by RedrootDEV** [comment]
Can u try the newest version pls?

**Comment by moodifofo** [comment]
كيفك شو اخباترك
