### ISSUE TITLE
Could not find whatsapp exe in order to create a desktop shorcut in windows 10

### ISSUE THREAD

**Issue by octaviobh** [RedrootDEV/WhatsAppDesktop-NoStore#6]
Hi !. Wonderful asset !. But where could I find the exe ? In what path ? Please write the answer to my octaviobh@yahoo.com or octaviobh@gmail.com 
Thanks in advance.
Octavio Baez.

**Comment by RedrootDEV** [comment]
> Hi !. Wonderful asset !. But where could I find the exe ? In what path ? Please write the answer to my [octaviobh@yahoo.com](mailto:octaviobh@yahoo.com) or [octaviobh@gmail.com](mailto:octaviobh@gmail.com) Thanks in advance. Octavio Baez.

https://www.reddit.com/r/whatsapp/comments/vwodk3/where_is_whatsapp_desktop_located_on_pc/

**Comment by fatcat386** [comment]
Hi, the same question. Your app is working and downloads/installs something but in the end there are no Whatsapp folder and/or executable. Did file search and checked packages folders. Nothing.
